all:
	gcc -std=c99 -pedantic -Werror -Wall -Wextra -Wvla -fsanitize=address -g 42sh.c ast/ast.c execution/execution.c expansion/expansion.c parser/parser.c lexer/lexer.c IO/input/input.c parser/print_parser.c -o test
